### PR TITLE
Fixed #1061 - updated preferences

### PR DESCRIPTION
**Pull request by AaronGreenhouse**

### CODE REVIEW

**Comment by philip-alldredge** [comment]
@lwrage are these changes something for @AaronGreenhouse for for myself? In any case, it might be best to merge any changes from develop into this branch before taking screenshots as the contents of the dialog may have changed.

**Comment by lwrage** [comment]
The comment was meant for @AaronGreenhouse

**Comment by AaronGreenhouse** [comment]
Updated help text and screen shot.

**Comment by philip-alldredge** [comment]
Be aware that the GE documentation is not setup to be automatically rebuilt. We typically rebuild it manually and commit the results, but rebuilding the user guide requires a few dependencies which are described in the readme. I can perform the rebuild if preferred.

**Comment by AaronGreenhouse** [comment]
Was going to try to build myself, but it seems I currently unable to install new software on my laptop.  (My local password has expired, and I don't know how to refresh it).  So it would be great if you can rebuild the docs please.

**Comment by philip-alldredge** [comment]
I've pushed the rebuilt user guide HTML.

**Comment by lwrage** [comment]
@philip-alldredge Could you merged this and regenerate the html from the merged markdown?

**Pull request merged**
