### PR TITLE
Shape image background

### PR DESCRIPTION
**Pull request by RyanMcilnay**
Ready for review.  Do not merge.

### CODE REVIEW

**Comment by philip-alldredge** [comment]
- There are multiple source files where single line comments have had their indention removed. Please look into and correct. The formatter appears to keep incorrect indention if a comment isn't indented at all.	
- Sometimes the quality of the scaled image is not very good. Try experimenting with the setAlias() and setInterpolation() methods of the graphics object to improve quality.
- The default image doesn't look very good sometimes after scaling. Is is problematic to just draw a rect box with black text at runtime that says "Unable to load image: <image path>". If this is done, remove the default image.
- Checking for whether an element can support an image. There is a place in LayoutUtil and AppearancePropertySection that checks if an image is compatible. Replace them with a method in DiagramElementPredicates. supportsImage(). Should require dock area to be null and the graphic to be an AgeShape. Connections may not have bendpoints so checking for bendpoints is not an appropriate check.		
- Image Paths. Currently a full path relative to the workspace and which is OS specific is being used. This is used in several places. Paths should be:
	- Relative to the project which contains the diagram. For example if the image is in an images folder in the project the path should be something like. "images/img.png". If it is in another project, it should be something like "../another_project/images/img.png"
	- In an operating system, independent format. Use toPortableString() instead of toOSString(). May have to change how path objects are created in other places in the code. I'm not sure the best way but it may be requires to create a path object with the portable string and then convert it to an OSString depending on usage.						
- ApperancePropertySection
	"Select an image from the tree:"  -> "Select an image."
	- List of image files. SWT may not support all the image files being checked. ImageIO is not part of SWT. I don't know of a way to check if a file is supported. For now, show BMP, PNG, JPEG, and TIF files.	
	- When an image is removed, the image path in the style should be set to null instead of an empty string.
	- Disable remove button if there isn't an image selected.
	- "Choose..." -> "Select..."
	- "Image:" -> "Show as Image:"			
- ImageGraphicsAlgorithmRendererFactory is creating the image. This is not the intended behavior. It should use find() to load an image that has already been created. LayoutUtil should be the only point where images are created. If it is unable to find the image, the unable to load image should be displayed. I believe this is currently a memory leak.					
- LayoutUtil
	- Don't supress exceptions when creating image. For this case, catch the specific exception and then rethrow it as a RuntimeException. I don't think there should ever be a malformed URL from a valid path. If there are exceptions that we are expecting, let's discuss.
	- Fix path issues.
	- Handle case that loading the image throws an exception. Should display the unable to load image error.
- GraphitiAgeDiagram
	- Path issues.
	- Resource Change Listener
		- Use a guava multimap for resourceChangedToDiagramElementMap.
		- getStyle() is confusingly named. Just have the contents inlined. Something like:					StyleBuilder.create(diagramElement.getStyle()).image(entry.getKey()).build()
		- Shouldn't need to use isNullOrEmpty on image or resource paths. If not-null, then it should be a valid path. This may requires changes to where the path is set.
	- getResourceIfReferencedByDiagram
		- Path issues.
		- Some OS are case sensitive. Should handle that appropriately. Eclipse may have a way of comparing paths in a platform independent way. Using Path objects may be the best way. Keep in mind that the path in the style is relative to the project when doing comaprisnos.
		- The name is inapropriate. It does not have anything to do with the diagram. 			
- Test on windows and linux
- Ecore/Style naming. Rename imageVisible to showAsImage.
- ImageFigure should handle case if image is null. In that case, show the unable to load image method.

**Comment by philip-alldredge** [comment]
@RyanMcilnay I have updated the previous comments based on our discussions.

**Comment by RyanMcilnay** [comment]
@philip-alldredge Ready for review again.

**Comment by philip-alldredge** [comment]
- Unable to load image message.
	- At certain zoom levels, some of the borders do not show. Need thicker border?
	- Move Unable to load image message to a tooltip.
	- Keep the image figure in all cases. In the error case make it have a distinctive appearance.			
- User Guide wording
	Improve wording.				
	Include list of file formats.

**Comment by RyanMcilnay** [comment]
@philip-alldredge Ready for review

**Comment by philip-alldredge** [comment]
Things are working really well but there are a couple area that needs improvements.
- Secondary labels such as subcomponent type labels currently allow an image to be set. This should be disabled.
- The layout for elements which are shown as an image should be improved before we merge. At a minimum, a minimum size needs to be set for such elements so that the aspect ratio matches that of the image. If an element is being shown as an image and has a current size, it would be nice to set the minimum size to the current size for elements which are being shown as an image. This would encourage the layout algorithm not to resize the image if the user has set a size. The minimum size is set in DiagramElementLayoutUtil.applyProperties().

- Suggested user manual text:
`- Elements can be shown as an image by selecting the the set image button and selecting *Select...* and then selecting the desired image. Whether the element is shown as an image or using standard notation can be toggled by selecting the *Show as Image* check box. The editor supports the following image file types: bmp, png, jpg, gif.`

Example of layout issues:
Bad:
example
Better:
example_ethernet

**Comment by philip-alldredge** [comment]
More thoughts
- Centering the image. Keep aspect ratio.
- Border
- Border Color
- Background Color
- Filter the select image dialog based on referenced projects.

**Comment by RyanMcilnay** [comment]
@philip-alldredge latest discussions have been implemented

**Comment by RyanMcilnay** [comment]
@philip-alldredge 
Elements can be displayed as an image by selecting the set image button, selecting <em>Select...</em>, and then selecting the desired image. Only images contained in referenced projects may be selected. _**Edit the project's properties to reference other projects**_. Whether an element is displayed as an image or using standard notation can be toggled by selecting the <em>Show as Image</em> check box. The editor supports the following image file types: bmp, png, jpg, gif.

The highlighted sentence seems out of place to me.  I'm not certain the sentence needs a change, so just let me know your thoughts.

New sentence option:
The project's properties can be edited to reference other projects.

**Comment by philip-alldredge** [comment]
How about. **To reference other projects, edit the project's properties.**

**Comment by RyanMcilnay** [comment]
@philip-alldredge Yeah that'll work, seems to be more consistent.  I can make the change and push it.

**Comment by philip-alldredge** [comment]
Thanks

**Pull request merged**
